# Generated by Django 2.1.2 on 2018-10-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_comment_dianzan'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='name',
            field=models.CharField(default='abc', max_length=128),
        ),
    ]
