# Generated by Django 2.1.2 on 2018-10-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20181016_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.CharField(default='abc', max_length=128),
        ),
        migrations.AddField(
            model_name='dianzan',
            name='time',
            field=models.CharField(default='abc', max_length=128),
        ),
    ]
