# Generated by Django 2.1.2 on 2018-10-16 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20181016_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='time',
            new_name='dataTime',
        ),
        migrations.RenameField(
            model_name='dianzan',
            old_name='time',
            new_name='dataTime',
        ),
    ]
