# Generated by Django 2.1.2 on 2018-10-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20181016_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='dataTime',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dianzan',
            name='dataTime',
            field=models.TextField(),
        ),
    ]
