# Generated by Django 2.1.2 on 2018-10-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20181016_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dianzan',
            name='dataTime',
        ),
        migrations.AddField(
            model_name='img',
            name='dataTime',
            field=models.CharField(default='abc', max_length=128),
        ),
        migrations.AlterField(
            model_name='comment',
            name='dataTime',
            field=models.CharField(default='abc', max_length=128),
        ),
    ]
