# Generated by Django 2.1.2 on 2018-10-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20181016_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='dataTime',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='img',
            name='dataTime',
            field=models.CharField(max_length=128),
        ),
    ]
