# Generated by Django 2.1.2 on 2018-10-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20181016_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='userid',
            field=models.IntegerField(default='abc'),
        ),
        migrations.AddField(
            model_name='dianzan',
            name='userid',
            field=models.IntegerField(default='abc'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='dataTime',
            field=models.CharField(default='abc', max_length=128),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(default='abc', max_length=128),
        ),
        migrations.AlterField(
            model_name='dianzan',
            name='number',
            field=models.CharField(default='abc', max_length=128),
        ),
    ]
