# Generated by Django 2.1.2 on 2018-10-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20181022_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='userid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dianzan',
            name='userid',
            field=models.IntegerField(default=0),
        ),
    ]
