# Generated by Django 2.1.2 on 2018-10-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_auto_20181022_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dianzan',
            name='userid',
            field=models.IntegerField(),
        ),
    ]
