# Generated by Django 2.1.2 on 2018-10-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_auto_20181022_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='dianzan',
            name='userid',
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.CharField(default='abc', max_length=32),
        ),
        migrations.AddField(
            model_name='dianzan',
            name='user_id',
            field=models.CharField(default='abc', max_length=32),
        ),
    ]
