# Generated by Django 2.1.2 on 2018-10-22 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_auto_20181022_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='usrid',
        ),
        migrations.RemoveField(
            model_name='dianzan',
            name='usrid',
        ),
    ]
