# Generated by Django 2.1.2 on 2018-10-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_auto_20181022_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='userid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dianzan',
            name='userid',
            field=models.IntegerField(default=0),
        ),
    ]
